Repository peter910820/KuroHelper, pull requests merged in 2025-09, with the labels that each got.

#4 feat: add erogs-fuzzy-search-music command
  bot/interaction.go
  bot/register.go
  erogs/music.go
  erogs/sql_template.go
  handlers/erogs_handler.go
  models/erogs/response.go
Labels: slash-command

#7 refactor: Refactor error handling(unify), unify VNDB request function…
  bot/interaction.go
  errors/errors.go
  handlers/erogs_handler.go
  handlers/vndb_handler.go
  models/vndb/response.go
  utils/error.go
  vndb/producer.go
  vndb/request.go
  vndb/staff.go
  vndb/stats.go
  vndb/vn.go
Labels: ✨enhancement, 💻slash-command, 🔧refactor

#8 ci: add build jobs of other branches on push
  .github/workflows/go.yml
Labels: ⚙️ci

#10 ci: add lint commits of workflows
  .github/workflows/go.yml
  tools/check_commit.go
Labels: ⚙️ci

#11 feat: add clean cache command
  .env.example
  bot/interaction.go
  bot/register.go
  erogs/creator.go
  erogs/music.go
  errors/errors.go
  handlers/management_handler.go
  utils/error.go
  utils/utils.go
  vndb/producer.go
  vndb/staff.go
  vndb/vn.go
Labels: 💻slash-command, ⭐feature

#17 ci: adjustment lint commits script to skip all merge push and PR check
  tools/check_commit.go
Labels: ⚙️ci

#18 Enhance/erogs search
  erogs/sql_template.go
  handlers/erogs_handler.go
  models/erogs/response.go
Labels: 🐛bug, 🔧refactor

#20 Ci/lint-commits
  tools/check_commit.go
Labels: ⚙️ci

#24 docs: add basic docs in README.md
  README.md
  docs/working-rules.md
  handlers/erogs_handler.go
Labels: 📖documentation, 🎀style

#27 Refactor/cache & pagination
  bot/interaction.go
  cache/cache.go
  handlers/cache.go
  handlers/erogs_handler.go
  handlers/management_handler.go
  handlers/pagination.go
  handlers/vndb_handler.go
  main.go
  models/common.go
  models/erogs/response.go
  models/vndb/basic.go
  models/vndb/factory.go
  models/vndb/response.go
  utils/make_component.go
Labels: 💻slash-command, 🔧refactor, 🎀style
