Repository peter910820/KuroHelper, pull requests merged in 2025-10, with the labels that each got.

#29 Ci/notify discord
  .env.example
  .github/workflows/event_send.yml
  .github/workflows/go.yml
  cmd/core/main.go
  cmd/corehttp/main.go
  go.mod
  go.sum
Labels: ⚙️ci, 🔧refactor

#31 Feature/search optimization
  .env.example
  bot/register.go
  config/config.go
  database/init.go
  database/migration.go
  erogs/creator.go
  erogs/game.go
  erogs/music.go
  erogs/search_opt.go
  go.mod
  go.sum
  handlers/erogs_handler.go
  models/db.go
  utils/utils.go
Labels: 💻slash-command, ⭐feature

#33 docs: supplement docs of version v1.1.0
  README.md
Labels: 📖documentation

#38 fix: fix seiya url bug
  provider/seiya/basic.go
Labels: 🐛bug

#39 release: v1.2.0
  README.md
Labels: 🎉release

#40 Hotfix/erogs search Release: v1.2.1
  provider/erogs/model.go
  provider/erogs/sql_template.go
Labels: 🐛bug, 🎉release

#43 chore: add game model display on game, brand and music search
  handlers/erogs_handler.go
  provider/erogs/model.go
  provider/erogs/sql_template.go
Labels: ✨enhancement

#46 fix(erogs): fix wrong tokuten count and enhance search logic
  provider/erogs/sql_template.go
Labels: 🐛bug, 🔧refactor
